spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  application:
    name: thisway

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  output:
    ansi:
      enabled: always

  security:
    debug: true

custom:
  verification-code-expiration-millis: 600000
  verification-code-key-prefix: ${CUSTOM_VERIFICATION_CODE_KEY_PREFIX:"verify:email:"}

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-validity-ms: ${JWT_ACCESS_TOKEN_VALIDITY_MS:86400000}

gps-log-collect-mode: ${GPS_LOG_COLLECT_MODE:direct}

kakao:
  rest-api-key: ${REST_API_KEY}

management:
  endpoints:
    web:
      exclude: "env,beans,metrics,threaddump"
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

