name: thisway

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: thisway-rabbitmq
    hostname: rabbitmq-dev
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management 콘솔
      - "15692:15692"    # Prometheus 메트릭
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
    networks:
      - dev-net
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_prometheus && rabbitmq-server"

  redis:
    image: redis:6.2
    container_name: thisway-redis
    ports:
      - "6379:6379"
    networks:
      - dev-net

  mysql:
    image: mysql:8.0
    container_name: thisway-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: thisway
    command:
      - --character-set-server=utf8mb4,
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - dev-net
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  prometheus:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    container_name: thisway-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - dev-net
    volumes:
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:12.0.2
    container_name: thisway-grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - dev-net
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  dev-net:
    driver: bridge

volumes:
  rabbitmq-data:
    driver: local
  mysql-data:
    driver: local
  prometheus_data:
    driver: local
  grafana-data:
    driver: local
