name: Build & Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 21 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Gradle 설정
        uses: gradle/actions/setup-gradle@v4

      - name: 애플리케이션 빌드
        run: ./gradlew clean bootJar

      - name: 빌드 아티팩트 업로드
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/libs/*.jar

  deploy:
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 아티팩트 다운로드
        uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - name: EC2로 JAR 복사
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "*.jar"
          target: "/home/ec2-user"

      - name: EC2에서 애플리케이션 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # (1) systemd 데몬 리로드 및 서비스 재시작
            sudo systemctl daemon-reload
            sudo systemctl restart thisway.service

            # (2) 서비스 상태 확인
            sudo systemctl status thisway.service --no-pager

            echo "Application started via systemd service."
