name: Build & Deploy

on:
  push:
    branches:
      - main
      - develop
      - feat/201-cd-test

env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com
  IMAGE_REPO: thisway/app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 21 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Gradle 캐시 설정 (선택)
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: AWS 자격증명 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Amazon ECR 로그인
        uses: aws-actions/amazon-ecr-login@v2

      - name: 컨테이너 이미지 빌드 & 푸시 (Jib)
        run: |
          ./gradlew clean jib \
            -Djib.to.image=$ECR_REGISTRY/$IMAGE_REPO

      - name: ECS 서비스 이름 조회
        id: find-service
        shell: bash
        run: |
          export AWS_PAGER=""

          {
            SERVICE_ARN=$(aws ecs list-services \
              --cluster thisway-cluster \
              --query "serviceArns[?contains(@, 'thisway-app-task-service')]" \
              --output text)
          } &> /dev/null

          SERVICE_NAME=${SERVICE_ARN##*/}
          echo "SERVICE=${SERVICE_NAME}" >> $GITHUB_OUTPUT

      - name: ECS 서비스 강제 재배포
        run: |
          aws ecs update-service \
            --cluster thisway-cluster \
            --service ${{ steps.find-service.outputs.SERVICE }} \
            --force-new-deployment
